// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0Rytsgk4BF3KBT4FllYovTrwjOzivtA',
    appId: '1:125673623279:web:f1d14e66962c9a9646951a',
    messagingSenderId: '125673623279',
    projectId: 'doobee-f42af',
    authDomain: 'doobee-f42af.firebaseapp.com',
    storageBucket: 'doobee-f42af.firebasestorage.app',
    measurementId: 'G-PBES0PSP3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOi5g0aG0dEHk4IKGzzCYzhtRWDQs3tI',
    appId: '1:125673623279:android:e48a49750e5ec13e46951a',
    messagingSenderId: '125673623279',
    projectId: 'doobee-f42af',
    storageBucket: 'doobee-f42af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sWRWj1y3hKnFrVN2Eb85sdOP2ut7n_c',
    appId: '1:125673623279:ios:c3c8336db49782c146951a',
    messagingSenderId: '125673623279',
    projectId: 'doobee-f42af',
    storageBucket: 'doobee-f42af.firebasestorage.app',
    iosBundleId: 'com.example.doobeeUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sWRWj1y3hKnFrVN2Eb85sdOP2ut7n_c',
    appId: '1:125673623279:ios:c3c8336db49782c146951a',
    messagingSenderId: '125673623279',
    projectId: 'doobee-f42af',
    storageBucket: 'doobee-f42af.firebasestorage.app',
    iosBundleId: 'com.example.doobeeUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ0Rytsgk4BF3KBT4FllYovTrwjOzivtA',
    appId: '1:125673623279:web:6bcd728ccce557c346951a',
    messagingSenderId: '125673623279',
    projectId: 'doobee-f42af',
    authDomain: 'doobee-f42af.firebaseapp.com',
    storageBucket: 'doobee-f42af.firebasestorage.app',
    measurementId: 'G-B9BTZK6SPW',
  );
}
